version: 2
jobs:
  build:
    docker:
      - image: codesimple/elm:0.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm.json" }}-{{ checksum "tests/elm.json" }}
      - run:
          name: Install sysconfcpus to fix core count detection
          command: |
            git clone https://github.com/obmarg/libsysconfcpus.git;
            cd libsysconfcpus;
            ./configure;
            make && make install;
            cd ..;
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Install elm dependencies
          command: sysconfcpus -n 2 elm make --yes
      - run:
          name: Build project
          command: sysconfcpus -n 2 make dist
      - run:
          name: Test project
          command: sysconfcpus -n 2 make test
      - save_cache:
          key:  v4-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm.json" }}-{{ checksum "tests/elm.json" }}
          paths:
            - elm-stuff
            - tests/elm-stuff
            - node_modules
