version: 2
jobs:
  build:
    docker:
      - image: codesimple/elm:0.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm-package.json" }}-{{ checksum "tests/elm-package.json" }}
            - v3-cache-{{ arch }}-{{ .Branch }}
            - v3-cache-{{ arch }}
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Install elm dependencies
          command: elm-make --yes
      - run:
          name: Build project
          command: make dist
      - run:
          name: Test project
          command: make test
      - save_cache:
          key:  v3-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "elm-package.json" }}-{{ checksum "tests/elm-package.json" }}
          paths:
            - elm-stuff
            - tests/elm-stuff
            - node_modules
      - save_cache:
          key: v3-cache-{{ arch }}-{{ .Branch }}
          paths:
            - node_modules
      - save_cache:
          key: v3-cache-{{ arch }}
          paths:
            - node_modules
